
start:
    value

value:
    number
    string-literal
    list
    object
    tfn

number:
    real-literal
    integer-literal

tfn: one of
    true
    false
    null

list:
    '[' list-contents? ']'

list-constents:
    value list-tail*

list-tail:
    ',' value?

object:
    '{' object-contents? '}'

object-contents:
    value ':' value object-tail*

object-tail:
    ',' value ':' value
    ','

