
<start>  : <value>
<value>  : <number>|<string>|<list>|<object>|<tfn>
<tfn>    : 'true'|'false'|'null'
<list>   : '['<list contents>']'
<object> : '{'<object contents>'}'

<list contents>   : <value><list tail>*|e
<list tail>       : ','<value>|','
<object contents> : <value>':'<value><object tail>*|e
<object tail>     : ','<value>':'<value>|','

<ignorewhite> : <wchar>|e
